---
title: "map_tag()"
resource_files:
- vft.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme: united
---

```{r, include=FALSE}
    # orientation: columns
    # social: menu
    # source_code: embed
    # navbar:
    #   - {href: "https://github.com/maurolepore", align: right, icon: fa-user}
    #   - {title: "Tutorial", 
    #     href: "https://bookdown.org/forestgeoguest/map_tag/map_tag.nb.html",
    #     align: left, icon: fa-file-text}
```

```{r global, include=FALSE}
library(flexdashboard)
library(map)
library(dplyr)
library(ggplot2)
library(icon)

vft <- readr::read_csv("vft.csv")
```

Adjust the arguments, and preview the effect
=======================================================================

--- DATA {data-width=350}
-----------------------------------------------------------------------

`r h1("Example data set")`

### Data were filtered to keep only one `PlotID` and one `QuadratName` {data-height=90}

```{r}
renderPrint({
  rngx <- paste0(range(vft$QX), collapse = " ")
  rngy <- paste0(range(vft$QY), collapse = " ")
  cat("range x: ", rngx, "\n", "range y: ", rngy, "\n", "\n", sep = "")
  
  vft
})
```

--- ARGUMENTS {data-width=250}
-----------------------------------------------------------------------

`r icon::fa_question_circle()` [`map_tag()`](https://forestgeo.github.io/map/reference/map_tag.html)

```{r}
textInput("site", "site_name", "My site, 2017")

fluidRow(
  column(6, numericInput("tagsize", "tag_size", 3)),
  column(6, numericInput("pointsize", "point_size", 1.5))
)

fluidRow(
  column(
    6, 
    sliderInput(
      "pointshape_alive", "point_shape (alive)", min = 1, max = 25, 19)
  ),
  column(
    6, 
    sliderInput(
      "pointshape_dead", "point_shape (dead)", min = 1, max = 25, 4)
  )
)
```

`r icon::fa_question_circle()` [`get_header()`](https://forestgeo.github.io/map/reference/get_header.html)

```{r}
textInput("line_1", "line1", pad(c("Checking: ", "Checked date: ")))
textInput("line_2", "line2", pad(c("Recording: "), total_width = 24))
textInput("line_3", "line3", pad(c("Measuring: ", "Measurement date: ")))
```

--- PLOT {data-width=350}
-----------------------------------------------------------------------

### Preview

```{r, fig.asp=1.15}
renderPlot({
  maps <- map_tag(
    vft, 
    site_name = input$site,
    point_size = input$pointsize,
    point_shape = c(input$pointshape_alive, input$pointshape_dead),
    tag_size = input$tagsize,
    header = get_header(
      line1 = input$line_1,
      line2 = input$line_2,
      line3 = input$line_3
    )
  )
  maps[[1]]
})
```

