                species
                spplist = NULL
                plotdim = c(1000, 500)
                xrange = c(0, plotdim[1])
                yrange = c(0, plotdim[2])
                elevdata = NULL
                cutoff = c(10, 100, 300, 3000)
                size = NULL
                deadtree = FALSE
                maintitle = ''
                titlepos = c(plotdim[1] / 2, 1.32 * plotdim[2])
                clrs = NULL
                bw = FALSE
                bgcolor = 'white'
                symbols = NULL
                xaxis = TRUE
                yaxis = TRUE
                addlegend = TRUE
                legpos = c(plotdim[1] / 2, 1.16 * plotdim[2])
                legsize = 0.75
                labsize = 1.15
                axisdiv = 100
                bty = 'n'
                ht = 6
                wd = 9
                plotside = 6
                axspos = 0.5
                topoclr = 'gray80'
                topoint = 0
                export = 'no'
                filepath = ''
                outfile = NULL
                
