---
title: "tmp_issues"
author: "maurolepore@gmail.com"
date: "22 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [#5](https://github.com/forestgeo/forestr/issues/5)

SOURCE OF PARAMS

- `abundance`, I mostly used ctfs, but I re-wrote for clarity. Common params:
    - censdata
    - type
    - alivecode
    - mindbh
    - dbhunit
    - split1
    - split2


- `findborderquads`
    - index Quadrate number, between 0 and 1249 in the standard plot.
    - dist Distance in m within which the neighboring quadrates are located. Distance is measured from any side of the index quadrate.
    - gridsize Side of the square quadrate, 20 x 20m by default.
    - plotdim Dimensions of the plot: east-west 1000m and north-south 500m

- `growth`

INHERITING PARAMS

Inherit from abundance:
- `abundance.spp`, Some args don't match.
- `biomass.change`
- `ba`

Inherit from `growth` 

- `growth.dbh`, returned value is complex. Consider adding details  from CRAN.
Must documment 

OTHER FUNCTIONS

- `assemble.demography`, Some argument names don't match.
- `elev.to.list`, may be deprecated. Converts a data.frame into a list, but this can be done with list(data.frame(x))
- `find.climits`
