---
name: Favorite Vignette
title: "Plot Species Distribution on .pdf"
subtitle: "An Example with data from Barro Colorado Island"
author: "Mauro Lepore"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 6
vignette: >
  %\VignetteIndexEntry{Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# hadley's settings
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,  # {mine}
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

options(dplyr.print_min = 6, dplyr.print_max = 6)
```

(Follows private issue https://github.com/forestgeo/forestr/issues/13)

# Load packages

```{r load-pkgs, message=FALSE, warning=FALSE}
# Ensure you installed all these packages; or install and load the tidyverse.
library(ggplot2)
library(dplyr)
library(purrr)

# Don't run
# forestr is still unavailable. Instead you should load the CTFS R package.
library(forestr)
```

# Load data

```{r load-data}
# Don't run. 
# I'm using bci for example. You should load your own data.
library(bci)
```

```{r}
cns_data <- bci::bci12full7
str(cns_data)
```

### Don't run

Filtering only 3 species for a minimal example.

```{r}
(species_selected <- unique(cns_data$sp)[1:3])
cns_data <- filter(cns_data, sp %in% species_selected)
```

### Functions

```{r}
# Plot gx gy.
plot_xy <- function(cns_data, ...) {
  ggplot(data = cns_data, aes(x = gx, y = gy)) +
    geom_point(...) +
    facet_grid(. ~ sp) +
    coord_fixed() +
    theme_bw()
}

# Wrap plotting and saving.
# Arguments:
#   cns_data: Census data.
#   ...: Arguments passed to `?geom_point()`.
sp_distribution_pdf <- function(cns_data, ...) {
  split_data_list <- split(cns_data, cns_data$sp)
  pdf
  purrr::walk(
    split_data_list, 
    plot_xy, 
    xlim = c(0, max(cns_data$gx, na.rm = TRUE)),
    ylim = c(0, max(cns_data$gy, na.rm = TRUE)), 
    ...
  )
}
```

# Run

Plot and save output as .pdf in working directory (nothing prints to scene).

```{r plot-and-save-as-pdf}
# Change point shape, color, fill, size, transparency: see `?geom_point()`.

cns_data_sub <- sample_n(cns_data, 1000)


plot_xy(cns_data_sub)


sp_unique <- unique(cns_data_sub$sp)
lapply(sp_unique, plot_xy)

```












